// <auto-generated />
using Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Entity.Migrations
{
    [DbContext(typeof(AeDbContext))]
    partial class AeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("Entity.Table.SysUser", b =>
                {
                    b.Property<string>("SysUserId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32);

                    b.Property<string>("Avatar")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(32);

                    b.Property<string>("Email")
                        .HasMaxLength(100);

                    b.Property<string>("Mobile")
                        .HasMaxLength(20);

                    b.Property<string>("NikeName")
                        .HasMaxLength(32);

                    b.Property<string>("Password")
                        .HasMaxLength(255);

                    b.Property<string>("QQ")
                        .HasMaxLength(200);

                    b.Property<string>("Remark")
                        .HasMaxLength(200);

                    b.Property<string>("Sex")
                        .HasMaxLength(1);

                    b.Property<int?>("Sort");

                    b.Property<int?>("Status");

                    b.Property<string>("TrueName")
                        .HasMaxLength(32);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<string>("UserType")
                        .HasMaxLength(1);

                    b.Property<string>("WX")
                        .HasMaxLength(200);

                    b.HasKey("SysUserId");

                    b.ToTable("Sys_User");
                });
#pragma warning restore 612, 618
        }
    }
}
